### ISSUE TITLE
Django Project Setup Using Poetry

### ISSUE THREAD

**Issue by gab-es21** [gab-es21/workoutsavings#1]
## Issue Description
This issue is focused on setting up a Django project using Poetry and configuring essential development tools like Black, Flake8, Isort, and Pre-commit for code formatting and quality checks.

## Tasks
- [x] Initialize a new Django project using Poetry.
- [x] Add necessary dependencies to the `pyproject.toml` file.
- [x] Configure Black for code formatting.
- [x] Configure Flake8 for code quality checks.
- [x] Configure Isort for import sorting.
- [x] Set up Pre-commit hooks for automated checks.
- [x] Verify that the development environment is correctly configured.
- [x] Create a sample Django app.
- [x] Verify that code formatting, linting, and import sorting work as expected.
- [x] Document the setup process for future reference.

### Initialize a New Django Project Using Poetry
1. Create a new directory for your Django project.
2. Inside the project directory, run the following command to initialize a new Python project using Poetry:
```
poetry init
```
Follow the prompts to configure your project.

### Add Dependencies to `pyproject.toml`
3. Open the `pyproject.toml` file generated by Poetry.
4. Add the necessary dependencies for Django and other project-specific packages.

### Configure Black for Code Formatting
5. Install Black using Poetry:

```
poetry add black --dev
```
6. Create a `.black` configuration file if needed.

### Configure Flake8 for Code Quality Checks
7. Install Flake8 using Poetry:
```
poetry add flake8 --dev
```
8. Create a `.flake8` configuration file if needed.

### Configure Isort for Import Sorting
9. Install Isort using Poetry:

```
poetry add isort --dev
```

10. Create an `isort.cfg` configuration file if needed.

### Set Up Pre-commit Hooks
11. Install Pre-commit using Poetry:

 ```
 poetry add pre-commit --dev
 ```

12. Create a `.pre-commit-config.yaml` file and define the hooks for Black, Flake8, and Isort.

### Verify Development Environment
13. Run the following command to ensure that the development environment is correctly configured:

 ```
 poetry install
 ```

### Create a Sample Django App
14. Create a sample Django app within your project.

### Verify Code Formatting and Quality Checks
15. Use the following commands to check code formatting, linting, and import sorting:

 ```
 poetry run black .
 poetry run flake8 .
 poetry run isort .
 ```

 Ensure there are no errors or warnings.

### Documentation
16. Document the setup process in the project's README or documentation for future reference.

## Additional Notes
- Make sure to follow best practices while writing code and adhere to the project's coding standards.
- Test your Django application thoroughly during development.
